// Code generated by "stringer -type=AchievementRank,AchievementCategory,AchievementLanguage"; DO NOT EDIT.

package igdb

import "strconv"

const _AchievementRank_name = "RankBronzeRankSilverRankGoldRankPlatinum"

var _AchievementRank_index = [...]uint8{0, 10, 20, 28, 40}

func (i AchievementRank) String() string {
	i -= 1
	if i < 0 || i >= AchievementRank(len(_AchievementRank_index)-1) {
		return "AchievementRank(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _AchievementRank_name[_AchievementRank_index[i]:_AchievementRank_index[i+1]]
}

const _AchievementCategory_name = "AchievementPlaystationAchievementXboxAchievementSteam"

var _AchievementCategory_index = [...]uint8{0, 22, 37, 53}

func (i AchievementCategory) String() string {
	i -= 1
	if i < 0 || i >= AchievementCategory(len(_AchievementCategory_index)-1) {
		return "AchievementCategory(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _AchievementCategory_name[_AchievementCategory_index[i]:_AchievementCategory_index[i+1]]
}

const _AchievementLanguage_name = "LanguageEuropeLanguageNorthAmericaLanguageAustraliaLanguageNewZealandLanguageJapanLanguageChinaLanguageAsiaLanguageWorldwideLanguageHongKongLanguageSouthKorea"

var _AchievementLanguage_index = [...]uint8{0, 14, 34, 51, 69, 82, 95, 107, 124, 140, 158}

func (i AchievementLanguage) String() string {
	i -= 1
	if i < 0 || i >= AchievementLanguage(len(_AchievementLanguage_index)-1) {
		return "AchievementLanguage(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _AchievementLanguage_name[_AchievementLanguage_index[i]:_AchievementLanguage_index[i+1]]
}
