// Code generated by "stringer -type=AchievementRank,AchievementCategory,AchievementLanguage"; DO NOT EDIT.

package igdb

import "strconv"

const _AchievementRank_name = "BronzeSilverGoldPlatinum"

var _AchievementRank_index = [...]uint8{0, 6, 12, 16, 24}

func (i AchievementRank) String() string {
	i -= 1
	if i < 0 || i >= AchievementRank(len(_AchievementRank_index)-1) {
		return "AchievementRank(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _AchievementRank_name[_AchievementRank_index[i]:_AchievementRank_index[i+1]]
}

const _AchievementCategory_name = "PlaystationXboxSteam"

var _AchievementCategory_index = [...]uint8{0, 11, 15, 20}

func (i AchievementCategory) String() string {
	i -= 1
	if i < 0 || i >= AchievementCategory(len(_AchievementCategory_index)-1) {
		return "AchievementCategory(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _AchievementCategory_name[_AchievementCategory_index[i]:_AchievementCategory_index[i+1]]
}

const _AchievementLanguage_name = "EuropeNorthAmericaAustraliaNewZealandJapanChinaAsiaWorldwideHongKongSouthKorea"

var _AchievementLanguage_index = [...]uint8{0, 6, 18, 27, 37, 42, 47, 51, 60, 68, 78}

func (i AchievementLanguage) String() string {
	i -= 1
	if i < 0 || i >= AchievementLanguage(len(_AchievementLanguage_index)-1) {
		return "AchievementLanguage(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _AchievementLanguage_name[_AchievementLanguage_index[i]:_AchievementLanguage_index[i+1]]
}
