// Code generated by "stringer -type=AgeRatingContentCategory"; DO NOT EDIT.

package igdb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AgeRatingContentPEGI-1]
	_ = x[AgeRatingContentESRB-2]
}

const _AgeRatingContentCategory_name = "AgeRatingContentPEGIAgeRatingContentESRB"

var _AgeRatingContentCategory_index = [...]uint8{0, 20, 40}

func (i AgeRatingContentCategory) String() string {
	i -= 1
	if i < 0 || i >= AgeRatingContentCategory(len(_AgeRatingContentCategory_index)-1) {
		return "AgeRatingContentCategory(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _AgeRatingContentCategory_name[_AgeRatingContentCategory_index[i]:_AgeRatingContentCategory_index[i+1]]
}
