// Code generated by "stringer -type=AgeRatingCategory,AgeRatingEnum"; DO NOT EDIT.

package igdb

import "strconv"

const _AgeRatingCategory_name = "AgeRatingESRBAgeRatingPEGI"

var _AgeRatingCategory_index = [...]uint8{0, 13, 26}

func (i AgeRatingCategory) String() string {
	i -= 1
	if i < 0 || i >= AgeRatingCategory(len(_AgeRatingCategory_index)-1) {
		return "AgeRatingCategory(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _AgeRatingCategory_name[_AgeRatingCategory_index[i]:_AgeRatingCategory_index[i+1]]
}

const _AgeRatingEnum_name = "AgeRatingThreeAgeRatingSevenAgeRatingTwelveAgeRatingSixteenAgeRatingEighteenAgeRatingRPAgeRatingECAgeRatingEAgeRatingE10AgeRatingTAgeRatingMAgeRatingAO"

var _AgeRatingEnum_index = [...]uint8{0, 14, 28, 43, 59, 76, 87, 98, 108, 120, 130, 140, 151}

func (i AgeRatingEnum) String() string {
	i -= 1
	if i < 0 || i >= AgeRatingEnum(len(_AgeRatingEnum_index)-1) {
		return "AgeRatingEnum(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _AgeRatingEnum_name[_AgeRatingEnum_index[i]:_AgeRatingEnum_index[i+1]]
}
