// Code generated by "stringer -type=DateCategory"; DO NOT EDIT.

package igdb

import "strconv"

const _CompanyDateCategory_name = "DateYYYYMMMMDDDateYYYYMMMMDateYYYYDateYYYYQ1DateYYYYQ2DateYYYYQ3DateYYYYQ4DateTBD"

var _CompanyDateCategory_index = [...]uint8{0, 14, 26, 34, 44, 54, 64, 74, 81}

func (i DateCategory) String() string {
	if i < 0 || i >= DateCategory(len(_CompanyDateCategory_index)-1) {
		return "DateCategory(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CompanyDateCategory_name[_CompanyDateCategory_index[i]:_CompanyDateCategory_index[i+1]]
}
