// Code generated by "stringer -type=DateCategory,RegionCategory"; DO NOT EDIT.

package igdb

import "strconv"

const _DateCategory_name = "DateYYYYMMMMDDDateYYYYMMMMDateYYYYDateYYYYQ1DateYYYYQ2DateYYYYQ3DateYYYYQ4DateTBD"

var _DateCategory_index = [...]uint8{0, 14, 26, 34, 44, 54, 64, 74, 81}

func (i DateCategory) String() string {
	if i < 0 || i >= DateCategory(len(_DateCategory_index)-1) {
		return "DateCategory(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DateCategory_name[_DateCategory_index[i]:_DateCategory_index[i+1]]
}

const _RegionCategory_name = "RegionEuropeRegionNorthAmericaRegionAustraliaRegionNewZealandRegionJapanRegionChinaRegionAsiaRegionWorldwide"

var _RegionCategory_index = [...]uint8{0, 12, 30, 45, 61, 72, 83, 93, 108}

func (i RegionCategory) String() string {
	i -= 1
	if i < 0 || i >= RegionCategory(len(_RegionCategory_index)-1) {
		return "RegionCategory(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _RegionCategory_name[_RegionCategory_index[i]:_RegionCategory_index[i+1]]
}
