// Code generated by "stringer -type=DateCategory,RegionCategory"; DO NOT EDIT.

package igdb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DateYYYYMMMMDD-0]
	_ = x[DateYYYYMMMM-1]
	_ = x[DateYYYY-2]
	_ = x[DateYYYYQ1-3]
	_ = x[DateYYYYQ2-4]
	_ = x[DateYYYYQ3-5]
	_ = x[DateYYYYQ4-6]
	_ = x[DateTBD-7]
}

const _DateCategory_name = "DateYYYYMMMMDDDateYYYYMMMMDateYYYYDateYYYYQ1DateYYYYQ2DateYYYYQ3DateYYYYQ4DateTBD"

var _DateCategory_index = [...]uint8{0, 14, 26, 34, 44, 54, 64, 74, 81}

func (i DateCategory) String() string {
	if i < 0 || i >= DateCategory(len(_DateCategory_index)-1) {
		return "DateCategory(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DateCategory_name[_DateCategory_index[i]:_DateCategory_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RegionEurope-1]
	_ = x[RegionNorthAmerica-2]
	_ = x[RegionAustralia-3]
	_ = x[RegionNewZealand-4]
	_ = x[RegionJapan-5]
	_ = x[RegionChina-6]
	_ = x[RegionAsia-7]
	_ = x[RegionWorldwide-8]
}

const _RegionCategory_name = "RegionEuropeRegionNorthAmericaRegionAustraliaRegionNewZealandRegionJapanRegionChinaRegionAsiaRegionWorldwide"

var _RegionCategory_index = [...]uint8{0, 12, 30, 45, 61, 72, 83, 93, 108}

func (i RegionCategory) String() string {
	i -= 1
	if i < 0 || i >= RegionCategory(len(_RegionCategory_index)-1) {
		return "RegionCategory(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _RegionCategory_name[_RegionCategory_index[i]:_RegionCategory_index[i+1]]
}
