// Code generated by "stringer -type=ExternalGameCategory"; DO NOT EDIT.

package igdb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExternalSteam-1]
	_ = x[ExternalGOG-5]
	_ = x[ExternalYoutube-10]
	_ = x[ExternalMicrosoft-11]
	_ = x[ExternalApple-13]
	_ = x[ExternalTwitch-14]
	_ = x[ExternalAndroid-15]
}

const (
	_ExternalGameCategory_name_0 = "ExternalSteam"
	_ExternalGameCategory_name_1 = "ExternalGOG"
	_ExternalGameCategory_name_2 = "ExternalYoutubeExternalMicrosoft"
	_ExternalGameCategory_name_3 = "ExternalAppleExternalTwitchExternalAndroid"
)

var (
	_ExternalGameCategory_index_2 = [...]uint8{0, 15, 32}
	_ExternalGameCategory_index_3 = [...]uint8{0, 13, 27, 42}
)

func (i ExternalGameCategory) String() string {
	switch {
	case i == 1:
		return _ExternalGameCategory_name_0
	case i == 5:
		return _ExternalGameCategory_name_1
	case 10 <= i && i <= 11:
		i -= 10
		return _ExternalGameCategory_name_2[_ExternalGameCategory_index_2[i]:_ExternalGameCategory_index_2[i+1]]
	case 13 <= i && i <= 15:
		i -= 13
		return _ExternalGameCategory_name_3[_ExternalGameCategory_index_3[i]:_ExternalGameCategory_index_3[i+1]]
	default:
		return "ExternalGameCategory(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
