// Code generated by "stringer -type=FeedCategory"; DO NOT EDIT.

package igdb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FeedPulseArticle-1]
	_ = x[FeedComingSoon-2]
	_ = x[FeedNewTrailer-3]
	_ = x[FeedUserContributedItem-5]
	_ = x[FeedUserContributionsItem-6]
	_ = x[FeedPageContributedItem-7]
}

const (
	_FeedCategory_name_0 = "FeedPulseArticleFeedComingSoonFeedNewTrailer"
	_FeedCategory_name_1 = "FeedUserContributedItemFeedUserContributionsItemFeedPageContributedItem"
)

var (
	_FeedCategory_index_0 = [...]uint8{0, 16, 30, 44}
	_FeedCategory_index_1 = [...]uint8{0, 23, 48, 71}
)

func (i FeedCategory) String() string {
	switch {
	case 1 <= i && i <= 3:
		i -= 1
		return _FeedCategory_name_0[_FeedCategory_index_0[i]:_FeedCategory_index_0[i+1]]
	case 5 <= i && i <= 7:
		i -= 5
		return _FeedCategory_name_1[_FeedCategory_index_1[i]:_FeedCategory_index_1[i+1]]
	default:
		return "FeedCategory(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
