// Code generated by "stringer -type=GameCategory,GameStatus"; DO NOT EDIT.

package igdb

import "strconv"

const _GameCategory_name = "MainGameDLCAddonExpansionBundleStandaloneExpansion"

var _GameCategory_index = [...]uint8{0, 8, 16, 25, 31, 50}

func (i GameCategory) String() string {
	if i < 0 || i >= GameCategory(len(_GameCategory_index)-1) {
		return "GameCategory(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GameCategory_name[_GameCategory_index[i]:_GameCategory_index[i+1]]
}

const (
	_GameStatus_name_0 = "StatusReleased"
	_GameStatus_name_1 = "StatusAlphaStatusBetaStatusEarlyAccessStatusOfflineStatusCancelled"
)

var (
	_GameStatus_index_1 = [...]uint8{0, 11, 21, 38, 51, 66}
)

func (i GameStatus) String() string {
	switch {
	case i == 0:
		return _GameStatus_name_0
	case 2 <= i && i <= 6:
		i -= 2
		return _GameStatus_name_1[_GameStatus_index_1[i]:_GameStatus_index_1[i+1]]
	default:
		return "GameStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
