// Code generated by "stringer -type=PageCategory,PageSubCategory,PageColor"; DO NOT EDIT.

package igdb

import "strconv"

const _PageCategory_name = "PagePersonalityPageMediaOrganizationPageContentCreatorPageClanTeam"

var _PageCategory_index = [...]uint8{0, 15, 36, 54, 66}

func (i PageCategory) String() string {
	i -= 1
	if i < 0 || i >= PageCategory(len(_PageCategory_index)-1) {
		return "PageCategory(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _PageCategory_name[_PageCategory_index[i]:_PageCategory_index[i+1]]
}

const _PageSubCategory_name = "PageUserPageGamePageCompanyPageConsumerPageIndustryPageESports"

var _PageSubCategory_index = [...]uint8{0, 8, 16, 27, 39, 51, 62}

func (i PageSubCategory) String() string {
	i -= 1
	if i < 0 || i >= PageSubCategory(len(_PageSubCategory_index)-1) {
		return "PageSubCategory(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _PageSubCategory_name[_PageSubCategory_index[i]:_PageSubCategory_index[i+1]]
}

const _PageColor_name = "PageGreenPageBluePageRedPageOrangePagePinkPageYellow"

var _PageColor_index = [...]uint8{0, 9, 17, 24, 34, 42, 52}

func (i PageColor) String() string {
	if i < 0 || i >= PageColor(len(_PageColor_index)-1) {
		return "PageColor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PageColor_name[_PageColor_index[i]:_PageColor_index[i+1]]
}
