// Code generated by "stringer -type=PlatformCategory"; DO NOT EDIT.

package igdb

import "strconv"

const _PlatformCategory_name = "PlatformConsolePlatformArcadePlatformPlatformPlatformOperatingSystemPlatformPortableConsolePlatformComputer"

var _PlatformCategory_index = [...]uint8{0, 15, 29, 45, 68, 91, 107}

func (i PlatformCategory) String() string {
	i -= 1
	if i < 0 || i >= PlatformCategory(len(_PlatformCategory_index)-1) {
		return "PlatformCategory(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _PlatformCategory_name[_PlatformCategory_index[i]:_PlatformCategory_index[i+1]]
}
