// Code generated by "stringer -type=ReviewCategory"; DO NOT EDIT.

package igdb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ReviewText-1]
	_ = x[ReviewVid-2]
}

const _ReviewCategory_name = "ReviewTextReviewVid"

var _ReviewCategory_index = [...]uint8{0, 10, 19}

func (i ReviewCategory) String() string {
	i -= 1
	if i < 0 || i >= ReviewCategory(len(_ReviewCategory_index)-1) {
		return "ReviewCategory(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ReviewCategory_name[_ReviewCategory_index[i]:_ReviewCategory_index[i+1]]
}
