// Code generated by "stringer -type=ReviewCategory"; DO NOT EDIT.

package igdb

import "strconv"

const _ReviewCategory_name = "ReviewTextReviewVid"

var _ReviewCategory_index = [...]uint8{0, 10, 19}

func (i ReviewCategory) String() string {
	i -= 1
	if i < 0 || i >= ReviewCategory(len(_ReviewCategory_index)-1) {
		return "ReviewCategory(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ReviewCategory_name[_ReviewCategory_index[i]:_ReviewCategory_index[i+1]]
}
