// Code generated by "stringer -type=SocialMetricCategory"; DO NOT EDIT.

package igdb

import "strconv"

const _SocialMetricCategory_name = "SocialFollowsSocialLikesSocialHatesSocialSharesSocialViewsSocialCommentsSocialFavorites"

var _SocialMetricCategory_index = [...]uint8{0, 13, 24, 35, 47, 58, 72, 87}

func (i SocialMetricCategory) String() string {
	i -= 1
	if i < 0 || i >= SocialMetricCategory(len(_SocialMetricCategory_index)-1) {
		return "SocialMetricCategory(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _SocialMetricCategory_name[_SocialMetricCategory_index[i]:_SocialMetricCategory_index[i+1]]
}
