// Code generated by "stringer -type=VersionFeatureInclusion"; DO NOT EDIT.

package igdb

import "strconv"

const _VersionFeatureInclusion_name = "NotIncludedIncludedPreOrderOnly"

var _VersionFeatureInclusion_index = [...]uint8{0, 11, 19, 31}

func (i VersionFeatureInclusion) String() string {
	if i < 0 || i >= VersionFeatureInclusion(len(_VersionFeatureInclusion_index)-1) {
		return "VersionFeatureInclusion(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VersionFeatureInclusion_name[_VersionFeatureInclusion_index[i]:_VersionFeatureInclusion_index[i+1]]
}
