// Code generated by "stringer -type=VersionFeatureCategory"; DO NOT EDIT.

package igdb

import "strconv"

const _VersionFeatureCategory_name = "VersionFeatureBooleanVerstionFeatureDescription"

var _VersionFeatureCategory_index = [...]uint8{0, 21, 47}

func (i VersionFeatureCategory) String() string {
	if i < 0 || i >= VersionFeatureCategory(len(_VersionFeatureCategory_index)-1) {
		return "VersionFeatureCategory(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VersionFeatureCategory_name[_VersionFeatureCategory_index[i]:_VersionFeatureCategory_index[i+1]]
}
