// Code generated by "stringer -type=VersionFeatureInclusion"; DO NOT EDIT.

package igdb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VersionFeatureNotIncluded-0]
	_ = x[VersionFeatureIncluded-1]
	_ = x[VersionFeaturePreOrderOnly-2]
}

const _VersionFeatureInclusion_name = "VersionFeatureNotIncludedVersionFeatureIncludedVersionFeaturePreOrderOnly"

var _VersionFeatureInclusion_index = [...]uint8{0, 25, 47, 73}

func (i VersionFeatureInclusion) String() string {
	if i < 0 || i >= VersionFeatureInclusion(len(_VersionFeatureInclusion_index)-1) {
		return "VersionFeatureInclusion(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VersionFeatureInclusion_name[_VersionFeatureInclusion_index[i]:_VersionFeatureInclusion_index[i+1]]
}
